language: node_js
node_js:
- '9'
sudo: required
services:
- docker
cache:
  yarn: true
  directories:
  - node_modules
  - api/node_modules
  - web/node_modules
  - e2e/node_modules
install:
- yarn install
- yarn setup:prisma
before_script:
- yarn build
script:
- yarn test:api
